Meta:
  description: Custom config for assembled form.
Inputs:
  formCustomVersion:
    name: formCustomVersion
    type: hidden
    value: "[CTF_DSP_Apr_2022]"
    form: dsp

Checklist:
  items:
    - name: Read the overview
    - name: Provide project info & contacts
    - name: Specify data to be deposited
    - name: Add governance info as needed
    - name: Submit this form
